services:
  - type: web
    name: solana-trading-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node solana_monitor_bot.js & node trading_bot_local.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: bot-data
      mountPath: /data
      sizeGB: 1
